/**
*	\file DPRDR7343_err.h
*	\brief Error codes 
*
*	This file contains all error codes of UML

    \author
*	\date 
*
*	\revision 
*	- Initial version
*	
*	\copyright Copyright (C) 2011 Data Patterns (India) Pvt. Ltd. / Indus Teqsite Pvt. Ltd. \n
*	All Rights Reserved.\n
*	Address: Plot # H9, Fourth Main Road, SIPCOT IT Park, Siruseri, \n
*   Off Rajiv Gandhi Salai (OMR), Pudupakkam P.O., \n
*   Chennai-603103 | India\n
*	Website : http://www.datapatternsindia.com/\n
*	Phone: 91-44-4741-4000\n
*	FAX: 91-44-4741-4444 \n
*	
*/
#ifndef _DP_RF_SIGGEN_WRAP_ERR_H_
#define _DP_RF_SIGGEN_WRAP_ERR_H_

/*********************DP SPECTRUM ANALYZER WRAPPER ERROR CODES**********************/
enum{
    DP_SIGGEN_SUCCESS = 0,
    DP_SIGGEN_ERR_INVALID_PARAM = -999,
    DP_SIGGEN_FREQ_CNFG_FAILURE,
    DP_SIGGEN_PWRLVL_CNFG_FAILURE,
    DP_SIGGEN_ALC_FAILURE,
    DP_SIGGEN_PRST_FAILURE,
    DP_SIGGEN_RFOP_FAILURE,
    DP_SIGGEN_RFAM_FAILURE,
    DP_SIGGEN_AM_SRC_FAILURE,
    DP_SIGGEN_AM_SCALING_FAILURE,
    DP_SIGGEN_AM_DEPTH_FAILURE,
    DP_SIGGEN_RFFM_FAILURE,
    DP_SIGGEN_MOD_DEV_FAILURE,
    DP_SIGGEN_MOD_SRC_FAILURE,
    DP_SIGGEN_RF_PHSMOD_FAILURE,
    DP_SIGGEN_PHSMOD_EXTSRC_FAILURE,
    DP_SIGGEN_PHSMOD_DEV_FAILURE,
    DP_SIGGEN_PULMOD_OPSIG_FAILURE,
    DP_SIGGEN_PUL_POL_FAILED,
    DP_SIGGEN_RFOP_PULMOD_FAILURE,
    DP_SIGGEN_EXT_POL_FAILURE,
    DP_SIGGEN_LFOP_FREQ_FAILURE,
    DP_SIGGEN_LFOP_WFM_FAILURE,
    DP_SIGGEN_LFOP_VOLT_FAILURE,
    DP_SIGGEN_LFGEN_ENA_FAILURE,
    DP_SIGGEN_INT_TRIG_FAILURE,
    DP_SIGGEN_CFG_SWMODE_FAILURE,
    DP_SIGGEN_CFG_TRIG_SRC_FAILURE,
    DP_SIGGEN_CFG_FREQ_SWEEP_FAILURE,
    DP_SIGGEN_CFG_CNTR_FREQ_FAILURE,
    DP_SIGGEN_LST_SEL_FAILURE,
    DP_SIGGEN_CFG_SPAN_FAILURE,
    DP_SIGGEN_CFG_DURA_FS_FAILURE,
    DP_SIGGEN_CFG_PWR_SWEEP_FAILURE,
    DP_SIGGEN_CFG_START_FAILURE,
    DP_SIGGEN_CFG_STOP_FAILURE,
    DP_SIGGEN_CFG_FREQ_MODE_FAILURE,
    DP_SIGGEN_CFG_FS_SRC_FAILURE,
    DP_SIGGEN_CFG_FREQ_START_FAILURE,
    DP_SIGGEN_CFG_FREQ_STOP_FAILURE,
    DP_SIGGEN_CFG_PWR_DWELL_FAILURE,
    DP_SIGGEN_CFG_PWR_PNTS_FAILURE,
    DP_SIGGEN_PWR_START_FAILURE,
    DP_SIGGEN_PWR_STOP_FAILURE,
    DP_SIGGEN_CFG_REF_OSC_FAILURE,
    DP_SIGGEN_CFG_ALC_FAILURE,
    DP_SIGGEN_ALC_SRC_FAILURE,
    DP_SIGGEN_ALC_BW_FAILURE,
    DP_SIGGEN_SLF_TST_QUERY_FAILURE,
    DP_SIGGEN_TRIG_SRC_FAILURE,
    DP_SIGGEN_CFG_FREQ_DWELL_FAILURE,
    DP_SIGGEN_CFG_FREQ_PNTS_FAILURE,
    DP_SIGGEN_FREQ_SWEEP_ENADIS_FAILURE,
    DP_SIGGEN_DIS_MOD_FAILURE,
    DP_SIGGEN_CFG_DURA_PS_FAILURE,
    DP_SIGGEN_MOD_CONFIG_FAILED,
    DP_SIGGEN_LST_MODE_FAILURE,
    DP_SIGGEN_LIST_FREQ_FAILURE,
    DP_SIGGEN_LIST_PWR_FAILURE,
    DP_SIGGEN_DISCONN_FAILURE,
    DP_SIGGEN_LIST_DWELL_FAILURE,
    DP_SIGGEN_LIST_TRIG_FAILURE,
    DP_SIGGEN_CFG_LIST_TYPE_FAILURE,
    DP_SIGGEN_CONT_INIT_FAILURE,
    DP_SIGGEN_CFG_LIST_DIR_FAILURE,
    DP_SIGGEN_CFG_LIST_DWELL_TYPE_FAILURE,
    DP_SIGGEN_PWR_MODE_LIST_FAILURE,
    DP_SIGGEN_INIT_IMM_FAILURE,
    DP_SIGGEN_MOD_DEV_FAILED,
    DP_SIGGEN_MOD_SRC_FAILED,
    DP_SIGGEN_PHSMOD_DEV_FAILED,
    DP_SIGGEN_OPEN_FAILURE,
    DP_SIGGEN_INT_ID_READ_FAILED,
    DP_SIGGEN_INT_INVALID_MODEL,
    DP_SIGGEN_CFG_FAILURE,
    DP_SIGGEN_INVALID_SGNO,
    DP_SIGGEN_PUL_PERIOD_FAILED,
    DP_SIGGEN_PUL_WIDTH_FAILED,
    DP_SIGGEN_DPUL_WIDTH_FAILED,
    DP_SIGGEN_PUL_DELAY_FAILED,
    DP_SIGGEN_READ_ID_ERROR
};

#endif
